export default {
  TOGGLE_DEMO_1: 'TOGGLE_DEMO_1',
  RESET_DEMO_1: 'RESET_DEMO_1',
  ADD_DEMO_2: 'ADD_DEMO_2',
  REMOVE_DEMO_2: 'REMOVE_DEMO_2',

  UPDATE_USER_LIST: 'UPDATE_USER_LIST',
  REMOVE_USER: 'REMOVE_USER'
};
