export default {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  MOVE_ITEM: 'MOVE_ITEM',

  REMOVE_USER: 'REMOVE_USER',

  ADD_TODO: 'ADD_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  DONE_TODO: 'DONE_TODO',
  MODIFY_TODO: 'EDIT_TODO'
};
